### ISSUE TITLE
x230 3rd party battery charging

### ISSUE THREAD

**Issue by Linvydas** [merge/skulls#108]
After flashing both (top and bottom) chips laptop can charge only genuine batteries. Is there some some way, mod or maybe a config option so that laptop could also charge 3rd party batteries?

**Comment by merge** [comment]
nope, that is what this project deals with: https://github.com/hamishcoleman/thinkpad-ec which is modifying the EC

**Comment by CanFixIt3242** [comment]
@merge @Linvydas Just a tip, if you run `thinkpad-ec` make sure to turn off keyboard-patch.
That is unless you want to use the x220 Keyboard on the x230. Otherwise, it re-maps your keys.

- https://github.com/hamishcoleman/thinkpad-ec/blob/master/docs/CONFIG.md
