### ISSUE TITLE
[Doc] Backup Bios

### ISSUE THREAD

**Issue by ggg27** [merge/skulls#109]
**Question/Documentation**: Is it possible to back up the factory-default BIOS?

Or is it listed somewhere in case users ever want to switch back?

_____________________

**Note**: Some OSes like [FreeBSD](https://www.reddit.com/r/freebsd/comments/952s7q/freebsd_on_coreboot_thinkpad_x230/), [NetBSD](https://www.coreboot.org/NetBSD), [OpenBSD](https://libreboot.org/docs/bsd/openbsd.html), Minix, e.c.t have had reports of issues with Coreboot installs. 

Luckily most of the issues appear to have been fixed, but would appreciate the ability to revert changes.

**Comment by asvc** [comment]
@ggg27 , you can dump it with something like `flashrom -r original.bin`.

**Comment by jcholsap** [comment]
Yes. Try it in circuit by making three copies and comparing the hashes. If the hashes don't compare then you may have power concerns. Some Lenovo mobos draw too much current and I have to pull the EEPROM  from the circuit to even read it.

**Comment by ggg27** [comment]
@asvc @jcholsap For some reason I missed this when reading the manual (haven't started flashing yet): `sudo ./external_install_bottom.sh -m -k <backup-file-to-create>`

Does that backup the original BIOS? What does that command do?

______________________________________

> @ggg27 , you can dump it with something like `flashrom -r original.bin`.

Alright, btw do any of you know how large the BIOS backup should be?
Also, would I need to tell it anything about the ports (haven't used `flashrom`)?

**Comment by asvc** [comment]
@ggg27 , 4mb top and 8mb bottom one. Please read the `man flashrom`.

**Comment by ggg27** [comment]
@asvc What you appear to be communicating about is the pin layout.

I was curious if I had to enter the layout to flashrom or if this was by default.

>  Please read the man flashrom.

Will do, thanks!
