### ISSUE TITLE
CPU throttling and fan speed behaviour less than ideal under Linux

### ISSUE THREAD

**Issue by Hermanio** [merge/skulls#112]
I have been running Skulls for some months now on my X230 and have been annoyed by issues with CPU throttling and fan speed behaviour that only occur under Linux. 

The CPU throttling behaviour is erratic, the clock speed jumps around between 1.8-3.1GHz and the Linux kernel would do a shutdown when temps reach 100-105C. The fan speed also ramps up to the max level around 80+C. These two issues can usually be controlled with managing `intel_pstate` and setting the fan level with commands such as `echo level 3 > /proc/acpi/ibm/fan`, but at temps of over 80+C these have no effect and are constantly overwritten.

I have found a workaround to this problem which is to add a kernel parameter `thermal.off=1` and then installing and running `thinkfan`. This results in the throttling and fan speed behaviour being identical to the one present under Windows 10. 

Is it a good idea to include such a workaround under a "Common issues and workarounds" section in the main README of this project? The actual cause is likely related to Coreboot and/or the way Linux kernel reads info from Corebooted machines, but as a quick workaround it's doing a great job on my machine and it will likely be helpful to other Skulls users, too.

**Comment by merge** [comment]
this issue is old and I haven't see such problem. I'm very happy with how the fan works and doubt that the bios plays a role here even. In case is still an issue an identified to be better with a different bios, then please re-open. thanks!
