### ISSUE TITLE
[Doc] Clarify if `BIOS Update (Utility & Bootable CD)` Can Be Written Onto USB

### ISSUE THREAD

**Issue by ggg27** [merge/skulls#113]
**Question/Doc**: Please clarify if [`BIOS Update (Utility & Bootable CD)`](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x230/downloads/ds029187) can be used on a USB drive or if it must use a CD.

**Comment by merge** [comment]
AFAIK it must be burnt to a CD. our docs actually mention "burn it". I'll go ahead an close this, so please re-open in case you have a specific change you want to have in our docs. thanks!
