### ISSUE TITLE
Please install dmidecode and run as root.

### ISSUE THREAD

**Issue by ggg27** [merge/skulls#114]
**Log**:

> ```
> root@debian:/home/usr/coreboot/skulls-x230-0.1.6# apt install dmidecode
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> dmidecode is already the newest version (3.2-1).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> root@debian:/home/usr/coreboot/skulls-x230-0.1.6# ./x230_skulls.sh
> Please install dmidecode and run as root.
> root@debian:/home/usr/coreboot/skulls-x230-0.1.6
> ```
> 

As you can see, I am under `su` and have `dmidecode`.

______________________

I just finished upgrading my BIOS

**Comment by pahakalle** [comment]
Do you get the same error if you run `dmidecode -t bios | grep Vendor | cut -d':' -f2`

**Comment by merge** [comment]
should be fixed by https://github.com/merge/skulls/commit/3ecfde0aea45b4ef69b19254b5c781823d1071d0
