### ISSUE TITLE
New BIOS update for x230

### ISSUE THREAD

**Issue by fjUSoF3CCTtX** [merge/skulls#123]
The x230 got a new BIOS update on 10/3/19, and it includes a new version of ECP. Is it preferable to use the most recent BIOS update with ECP 1.15, or to use the previous update with ECP 1.14?

The advisory
https://support.lenovo.com/us/en/solutions/len-27764

**Comment by jcholsap** [comment]
If you are modding your BIOS in anyway, then it's preferable *not* to update at all. My understanding is that the updates as of this year "fix" security "problems", i.e., locks out the BIOS for modding.

**Comment by tlaurion** [comment]
More information [here](https://github.com/hamishcoleman/thinkpad-ec)

**Comment by fjUSoF3CCTtX** [comment]
Thanks.
