### ISSUE TITLE
Bottom chip isn't being detected

### ISSUE THREAD

**Issue by fjUSoF3CCTtX** [merge/skulls#125]
Was able to flash the top chip with no issue, but the bottom chip is not detected after multiple attempts using a RasberryPi 2. The instructions are to manually identify the chip and us the -c command. I have tried looking around for how to do that with no success.

The computer boots just fine with SeaBios, so it isn't bricked. Is it possible for the computer to work with a non functioning bottom chip?

---- 

Got it figured out. For those who run into the issue. I noticed that after the prompt saying that no chip was recognized that is said the the spi identified the chip "W25Q64.V". I decided to run `sudo ./external_install_bottom.sh -c W25Q64.V`. It worked for recognizing the chip. Some of the output said that the chip would not be cleaned, but it would be unlocked. After that I ran `sudo ./external_install_bottom.sh -c W25Q64.V -m -k <backup-file-to-create>` and everything worked correctly.

**Comment by merge** [comment]
ok thanks for that update. flashing the bottom chip is optinal though (should be mentioned in the docs). if not flashed, your flash is write-protected (and ME is not cleaned).

it sometimes comes up that we would be able to use more than the 4M bios. if we would do so, you would not have been able to boot after flashing the  top chip only. so staying at 4M is our "feature" here.
