### ISSUE TITLE
Update plan?

### ISSUE THREAD

**Issue by kamilr** [merge/skulls#129]
Is there planned update due to [SeaBios 1.13.0](https://seabios.org/Releases#SeaBIOS_1.13.0) was released?

Best regards.

**Comment by merge** [comment]
thanks for the reminder. I've put up an update-patch: https://review.coreboot.org/c/coreboot/+/37631 When it's in coreboot, we should plan to release, yes.

**Comment by kamilr** [comment]
Thanks a lot!

**Comment by merge** [comment]
just released version 0.1.8 with seabios 1.13.0. please test
