### ISSUE TITLE
Clarification of RPi3 hardware example

### ISSUE THREAD

**Issue by k3tan172** [merge/skulls#138]
In the diagram of the README, there are 2 GND pins and a TX and an RX pins. Is the GND/TX/RX that are next to each other required to be used? The hardware requirements say only 6 jumper wires are required. Not using the GND/TX/RX that are next to each other is the only way this makes sense, unless I'm missing something.

Please advise.

**Comment by jcholsap** [comment]
Personally, I find it easiest to use pins 17, 19, 21, 23, 25 and 24. I have a keyboard and monitor attached to my RPI and, so, don't need TX and RX.
![Raspberry pi I2C pins](https://user-images.githubusercontent.com/30509348/74100679-9d09c300-4aff-11ea-93ee-7dbaf66f9fec.png)

**Comment by k3tan172** [comment]
This is excellent. Thank you for clarification.
