### ISSUE TITLE
X230 Ultrabase 3 issue

### ISSUE THREAD

**Issue by larghio** [merge/skulls#147]
Everything works when docked except undock button. undock light and my hardrive  that I installed in the dock in a ultrabay hdd caddy. dvd also does not work. confirmed works with lenovo bios.
Great effort btw :)

**Comment by digmorepaka** [comment]
Undock button is not needed with any modern OS on this machine. Every interface on it is hotplug capable by spec. In the devicetree.cb the dock sata is enabled, try doing a clean build and trying again. If you happen to have a 4338 pr 4337 desktop dock with eSata, try if it's eSata works.

**Comment by larghio** [comment]
Hi . I agree about the dock. Just a observation. I got my ultrabay hdd to show up.
If I do a cold boot it works. if I dock with the power on or in S3 suspend. No hdd. nothing hdd related in the logs.
