### ISSUE TITLE
x230 instructions broken when checking out latest release

### ISSUE THREAD

**Issue by orzival** [merge/skulls#181]
Hi, I started by checking out the latest release and followed the instructions in `x230/README.sh`. However, running `./x230_skulls.sh -U` gives

```
You seem to use a development version. Please use release package skulls-x230 0.0.2 for flashing.
```

I see that this has been fixed since 3f7ed3138b0747563b83e10a8e842811f7f27c1c. Can that fix be released?

**Comment by merge** [comment]
release done. is this fixed?

**Comment by merge** [comment]
since this is fixed, but also should be obsolete with the latest refactorings, closing.
