### ISSUE TITLE
T430 bottom chip flashing issue

### ISSUE THREAD

**Issue by boraboragoldfish** [merge/skulls#189]
Hi Martin. Thank you for working on the T430. I am having issues while trying to flash my T430's bottom chip (Skulls 1.0.0.) I was though successful in flashing the top chip but the bottom one gives me the following output:

sudo ./external_install_top.sh -b t430 -k factory_topchip.rom
1) ./x230_coreboot_seabios_free_4de7610b32_top.rom   5) ./x230t_coreboot_seabios_free_4de7610b32_top.rom
2) ./x230_coreboot_seabios_4de7610b32_top.rom	     6) ./factory_bottomchip.rom
3) ./x230t_coreboot_seabios_4de7610b32_top.rom	     7) Quit
4) ./t430_coreboot_seabios_4de7610b32_top.rom
Please select a file to flash or start with the -i option to use a different one: 4
Please select the hardware you use:
1) Raspberry Pi
2) CH341A
3) Quit
Please select the hardware flasher: 2
_trying to detect the chip...
chip not detected.
flashrom v1.2 on Linux 5.4.0-70-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Found Winbond flash chip "W25Q32.V" (4096 kB, SPI) on ch341a_spi.
No operations were specified.
Please find it manually in the list above and rerun with the -c parameter._

I am able to get a read on the chip.

_$ sudo flashrom -p ch341a_spi
flashrom v1.2 on Linux 5.4.0-70-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Found Winbond flash chip "W25Q32.V" (4096 kB, SPI) on ch341a_spi.
No operations were specified._

I have also tested with 2 units of eeprom clips and CH341a and they all seem to be able to detect the chip. Wonder if I did something wrong. Thanks!

**Comment by merge** [comment]
thank you for that report! indeed there was one chip variant missing. If you can, please download the external_install_top scrip from the master branch and test again. thanks again.
