### ISSUE TITLE
Broken link in T430 documentation

### ISSUE THREAD

**Issue by kevinmxyz** [merge/skulls#196]
While reading the T430 documentation, I found a link to the coreboot docs that is broken. I think the issue is caused by coreboot's re-organization of their docs.

Location in skulls documentation: https://github.com/merge/skulls/blob/master/t430/README.md#why-does-this-work

Link text: "coreboot documentation"

Broken URL: https://doc.coreboot.org/mainboard/lenovo/xx30_series.html

I think the intended destination is: https://doc.coreboot.org/mainboard/lenovo/t430.html

**Comment by merge** [comment]
thanks!
