### ISSUE TITLE
how to make a one-time donation?

### ISSUE THREAD

**Issue by bdantas** [merge/skulls#219]
Hi, Martin. Thank you for skulls. My personal machine is an X230 with coreboot thanks to skulls. I'd like to make a one-time donation as a small token of gratitude but the "sponsors" section of your github page only shows how to donate monthly. What's the best way to send you a one-time donation?

**Comment by merge** [comment]
if you send me an email I'm glad to give you a BTC address of mine for example. wire transfer would probably work too, but that please via email. this should be a community project - or at least part of the wider coreboot community :) Can I close this? If not, please reopen. thanks for asking!
