### ISSUE TITLE
./build.sh

### ISSUE THREAD

**Issue by Lchvo** [merge/skulls#229]
Hi, when i try yo build (for change the bootsplash) i get this msg:

./build.sh : 90: docker: not found

i have installed docker via:

Sudo apt-get install docker

How i can fix this?

Regards.

**Comment by merge** [comment]
I think it's docker.io

**Comment by Lchvo** [comment]
> I think it's docker.io

Uoooo simply AF! That was the problem! 

Once time i generate the build, how i can flash ot internally? I can't find in the readme.md

Lot of thanks

**Comment by merge** [comment]
you can use the main `./skulls.sh` script to flash internally, but please open a different issue when you have a problem with the README. thanks!
