### ISSUE TITLE
Feature request: Any hopes for the w530?

### ISSUE THREAD

**Issue by RHL120** [merge/skulls#232]
Hi, I have ordered a W530 but then found out that Skulls has not been ported to it. Are there any plans to port Skulls to the W530?
Thanks

**Comment by darnrain** [comment]
You can use [](https://github.com/n4ru/1vyrain) to install custom stock bios on the w530.

**Comment by RHL120** [comment]
> You can use https://github.com/n4ru/1vyrain to install custom stock bios on the w530.

Yes, I know but I want to flash coreboot.

**Comment by student-sx** [comment]
If the T530 works, why not also the W530? What's the essential difference here?

**Comment by RHL120** [comment]
> If the T530 works, why not also the W530? What's the essential difference here?

I have no idea, I am not bios expert

**Comment by merge** [comment]
I'll try to add the W530 soon

**Comment by RHL120** [comment]
> I'll try to add the W530 soon

Ok thanks
