### ISSUE TITLE
Feature Request: T410s support

### ISSUE THREAD

**Issue by stradicat** [merge/skulls#241]
Good day, Skulls team!

Does the T410s look anywhere near feasable?
It's got an Ironlake dual-core, 4-threaded processor with integrated Intel HD video and an Nvidia NVS3100M discrete GPU.

If it looks like it could be done, let me know so I can sponsor at least a part of the effort.

**Comment by merge** [comment]
coreboot config says T410 is supported, not T410s. I don't have any of these so I can't say more than that. We just build what coreboot supports here. Questions like this should go to coreboot.

**Comment by valtoree** [comment]
@stradicat how did u go? I too have a t410s wanting to put core boot on.
