### ISSUE TITLE
Unable to load thinkpad_acpi

### ISSUE THREAD

**Issue by karstenes** [merge/skulls#248]
Hi, I have been trying to get thinkpad_acpi to load on arch with the latest skulls. 

I try modprobe:
`❯ sudo modprobe thinkpad_acpi`

`modprobe: ERROR: could not insert 'thinkpad_acpi': No such device`

and force:
`❯ sudo modprobe thinkpad_acpi --force`

`modprobe: ERROR: could not insert 'thinkpad_acpi': Key was rejected by service`

Is coreboot causing this? All I see on google about it is secure boot which makes no sense seeing as I am running skulls.

Thank you!

**Comment by Sokoloft** [comment]
I'm having the same issue with my thinkpad x250 and I have opencore for a hackintosh install.
