### ISSUE TITLE
cb_in: error: LIBUSB_TRANSFER_TIMED_OUT

### ISSUE THREAD

**Issue by computative** [merge/skulls#251]
I have a usb CH341A programmer with external power supply 3v3 1A. The Pomona clip is used to connect the outputs that are labeled CS, MISO, MOSI, CLK on the programmer with the same labels on the diagram chip diagram. The power supply ground is connected to ground on the Pomona clip and to the ground of the programmer. The 3v3 of the power supply is connected to 3v3 on the clip and 3v3 on programmer. I have tried two different debian computers with similar results:
```
$ sudo ./external_install_bottom.sh -m -k backup-lower.bin
Skulls

Please select the hardware you use:
1) Raspberry Pi
2) CH341A
3) Exit
Please select the hardware flasher: 2
Ok. Connect a CH341A programmer
trying to detect the chip...
Detected MX25L6406E/MX25L6408E.
make: Går til katalog "/home/marius/Nedlastinger/skulls-1.0.5/util/ifdtool"
make: Forlader katalog "/home/marius/Nedlastinger/skulls-1.0.5/util/ifdtool"
Intel ME will be cleaned.
The flash ROM will be unlocked.
Start reading 2 times. Please be patient...
flashrom v1.2 on Linux 5.10.0-18-amd64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Found Macronix flash chip "MX25L6406E/MX25L6408E" (8192 kB, SPI) on ch341a_spi.
Reading flash... 
cb_in: error: LIBUSB_TRANSFER_TIMED_OUT
ch341a_spi_spi_send_command: Failed to read 4100 bytes
libusb: warning [handle_timeout] async cancel failed -5
Read operation failed!
FAILED.
```

I have been able to use the programmer to flash libreboot on some X200-thinkpads without any issues. What's the appropriate way to debug and solve the problem I describe?

**Comment by computative** [comment]
I solved it. The fist thing that I tried and that worked was to install Debian 9. I'll donate $50.

**Comment by merge** [comment]
> I solved it. The first thing that I tried and that worked was to install Debian 9 (oldoldstable). I'll donate $50.

thanks a lot. that is awefully nice, really. I'll take the freedom to close this issue then.
