### ISSUE TITLE
Please use flashrom v1.2 or later. You seem to use .

### ISSUE THREAD

**Issue by SKELETONTOPROM** [merge/skulls#266]
My flashrom version is:

flashrom is already the newest version (1.3.0-2.1)

But I get this error when trying to update:

~/Downloads/skulls-1.0.7$ sudo '/home/myusername/Downloads/skulls-1.0.7/skulls.sh' -b x230 -v

Board: x230
Please use flashrom v1.2 or later. You seem to use .

**Comment by matsura8** [comment]
I had the same problem (In my case, Kali 2023. When I ran 'flashrom -v' the output declared it was an unspecified version number even though it stated v1.3 when installing with apt. The version number must have not been specified properly in the release. I would try installing from another source or compiling your own flashrom files. Flashrom also has precompiled binaries for most distros.

**Comment by matsura8** [comment]
It seems like ~/flashrom-1.3.0/util/getversion.sh --version is returning undefined all the time, so it would be ideal to modify code keep this issue from persisting in all other builds.

**Comment by matsura8** [comment]
The updated code though still gives error and does not allow to proceed. It appears the lack of version number was included in their release tarball. I have notified flashrom dev already.

**Comment by matsura8** [comment]
After repairing the flashrom code myself...
![Screenshot_2023-06-04_17-51-34](https://github.com/merge/skulls/assets/33567097/90ef3655-a738-4a42-838a-3e75768c9531)
