### ISSUE TITLE
GRUB settings after new update

### ISSUE THREAD

**Issue by mrbpp** [merge/skulls#282]
Do I need to revert the GRUB changes in `/etc/default/` from `iomem=relaxed` back to `quiet splash` after successfully updating the Skulls version Internally?

`./skulls.sh -b x230 -U`
`You are using the latest version of Skulls`

**Congrats on the new release `v1.1.0` everyone!**

**Comment by mrbpp** [comment]
Can someone label this as a `question` ?

**Comment by merge** [comment]
You don't *need* to. But yes, it's advised to remove `iomem=relaxed` from the kernel commandline again if you don't need it. You simply have better security properties during runtime.
