### ISSUE TITLE
Error update skulls

### ISSUE THREAD

**Issue by Kzlztan** [merge/skulls#288]
![スクリーンショット_2024-03-30_14-17-27](https://github.com/merge/skulls/assets/165491264/efa2ceb2-1587-4986-a783-27fa3c8361e3)
![スクリーンショット_2024-03-30_14-18-37](https://github.com/merge/skulls/assets/165491264/dbfa0c1d-8bd4-425d-a2c0-2c961b2da10d)

how can I solve this problem?

**Comment by merge** [comment]
try when being logged in as root, without using sudo. does the same error happen?

**Comment by Kzlztan** [comment]
![スクリーンショット_2024-04-02_11-30-34](https://github.com/merge/skulls/assets/165491264/52994f97-4085-4d5a-96af-7d117b212d3a)
same error

**Comment by Kzlztan** [comment]
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
after I use this, apparently the update was successful.

how can I check i succeed to update?

**Comment by Kzlztan** [comment]
thank you. it was new version
