### ISSUE TITLE
Maybe using skulls config within heads nightly build

### ISSUE THREAD

**Issue by nemanjan00** [merge/skulls#29]
I have just created build enviroment for building heads nightly. 

I figured out  most of things I do not like about heads are solved by your config. 

Do you think we can collaborate in some way to make it better? 

https://github.com/nemanjan00/heads-ci

**Comment by merge** [comment]
Shouldn't things you don't like about Heads be resolved in the Heads project directly? What would you change?

thanks

**Comment by nemanjan00** [comment]
The biggest problem with heads is lack of nvram settings... 
Second thing is graphics initialization...

**Comment by merge** [comment]
please re-open in case there is a suggestion on how to change Skulls. thanks.
