### ISSUE TITLE
[Question] Full disk encryption

### ISSUE THREAD

**Issue by VoidWa** [merge/skulls#296]
Hello. I have a x230 currently running arch linux and [grub](https://aur.archlinux.org/packages/grub-improved-luks2-git) bootloader with patches for luks2 and argon2 for full disk encryption. I'm planning to install Skulls on this computer using 1vyrain, but I don't know if grub supports FDE and how to use it?

Thank you.

**Comment by merge** [comment]
If you use a Skulls image as we build it, that does not include GRUB. It includes SeaBIOS that will execute your disk's GRUB similar to the Lenovo BIOS. I can't say much about the 1vyrain installation method though as I don't use it.

**Comment by VoidWa** [comment]
I need to rebuild the image to use GRUB instead of SeaBIOS... OK, Thank you.
