### ISSUE TITLE
Please clarify X230 Tablet Support

### ISSUE THREAD

**Issue by batonac** [merge/skulls#47]
Your readme states that the X230 is supported, but I'm not an expert enough to know for sure if that includes the X230t as well. Could you update your readme to explicitly affirm or deny support for this variant? Thank-you!

**Comment by merge** [comment]
Thanks for bringing this up. I can confirm here that the X230t is supported as well. coreboot doesn't make a difference.

Although I personally can't test this, it seems like I could add it to the docs. And if anybody else is faster and sends a PR I'm not unhappy either :)
