### ISSUE TITLE
Clarify the difference between the free and nonfree image

### ISSUE THREAD

**Issue by varac** [merge/skulls#56]
It would be great to clarify the difference between the free and nonfree image in the x230 README.
I.e.

- Do both images work (for everybody) ?
- If not, why ?
- What are the (expected/known) issue with the free image ?
- Is there anything that a user can do to use the free image is failing out of the box ?

**Comment by DanitiKain** [comment]
Yes I would love to know this information as well.

**Comment by merge** [comment]
Would you like to review my pull request? Any objections or missing improvements? thanks!

**Comment by merge** [comment]
thanks for reviewing. is this better? I'll merge this soon if there aren't any objections.

**Comment by DanitiKain** [comment]
I think that is good enough.
