### ISSUE TITLE
Swap fn and ctrl key

### ISSUE THREAD

**Issue by DanitiKain** [merge/skulls#57]
I would love if one of the bios already had the fn and ctrl key swapped. Chatting in the coreboot irc channel and searching the web has not produce much results in how to make this happen. So just having it ready for those that one it from the get go would be great. I feel it is something that most thinkpad owners change more than any other bios setting. The other option I think would be creating a resource on this project for how to do it if you don't want to include it in the bios release would be very helpful for those that want to do it.

**Comment by explit7** [comment]
keys settings are stored not in the BIOS, they are stored in the EC (Embedded controller)
You can patch Embedded Controller Settings (also Fn - Ctrl Key swap) as long, as you have Original Lenovo BIOS Installed.
After you patched it - the change will be stored permanently.
Afterwards you can install Heads, Skulls or Coreboot.

For patching see here:
https://github.com/hamishcoleman/thinkpad-ec

**Comment by DanitiKain** [comment]
Ok before flashing skullls I had this setting saved. Should it be saved or do I now have to flash to original bios back and set the settings via link above. Also if I have to flash back what are the risks of doing this?

**Comment by merge** [comment]
if you already have this EC modification _now_, this will be saved if you flash a coreboot BIOS like Skulls. We don't change the EC firmware here.

**Comment by DanitiKain** [comment]
Ok to be more clear I was running stock bios. I had this settings set before flashing with Skulls. I have 4 thinkpads and I have all of them set this way. After flashing I booted into OS and it kept not working I thought it had messed the keyboard up then I realized ahh maybe I need to set in the bios. Now that is why I am here because it is so easy to just set. So if the settings from old Lenovo Bios EC settings should apply then that is an issue because they are not applying at the moment after I flashed skulls.

**Comment by apraile** [comment]
Try this:

- In the SeaBIOS boot menu, select `2. Payload [nvramcui]`
- Enable `fn_ctrl_swap` option

The configuration is maintained between reboots. It works for me.

**Comment by DanitiKain** [comment]
@apraile wow it was really that easy. How did #coreboot on IRC channel not know this.  Everyone was pointing to the above https://github.com/hamishcoleman/thinkpad-ec and talking about patching.

**Comment by merge** [comment]
should we link to https://www.coreboot.org/Payloads#nvramcui which doesn't have much information either?

maybe try to create an official documentation page for nvramcui in coreboot? that might take time...
