### ISSUE TITLE
Updating best-practices

### ISSUE THREAD

**Issue by varac** [merge/skulls#68]
The [x230 updating](https://github.com/merge/skulls/tree/master/x230#updating) are very terse.
As a burnt child who already bricked it's x230 by flashing skulls (using external power from the flasher to the chip), I got cautious.

```
Instead you can run the update directly on your X230 using Linux. That's of course very convenient - just install flashrom from your Linux distribution - but according to the flashrom manpage this is very dangerous:
```
How do ppl update skulls ? Is it a common practice to flash internally ? Are there reports of bricked x230s by updating them internally ? As I said, I bricked my x230 by flashing externally, so I'm wonder if my method is any safer than updating internally.

Please add some more information to this section. Thx !

**Comment by merge** [comment]
yes, we should change the documentation, see #49 
Im my view it's totally best practice to flash internally and i've not heard of any problems on the x230.
