### ISSUE TITLE
Describe the project on https://doc.coreboot.org/distributions.html

### ISSUE THREAD

**Issue by pgeorgi** [merge/skulls#72]
We're currently reworking the coreboot documentation system and as part of that I recently started a list of coreboot distributions. I guess this project fits that description pretty well, but it may be best if you (skulls devs) describe your project in your own words.

The page is generated from coreboot's Documentation/distributions.md, so I invite you to propose a change in upstream coreboot to add yourself. If you add me as reviewer, I'll gladly see that it's taken care of.

**Comment by merge** [comment]
yes, why not: https://review.coreboot.org/c/coreboot/+/31463
discussion is now over there,
thanks
