### ISSUE TITLE
me_cleaner applied command different then Heads

### ISSUE THREAD

**Issue by tlaurion** [merge/skulls#76]
https://github.com/merge/skulls/blob/c20203d8be5f704949743b17e6ed9ae784f124b5/x230/external_install_bottom.sh#L228

vs

https://github.com/osresearch/heads-wiki/blame/master/Clean-the-ME-firmware.md#L31
`python me_cleaner.py -r -t -d -S -O clean_flash.bin flash.bin --extract-me extracted_me.rom`

The latter deletes unused modules as -S while truncating unused space (-t), removing R/W permission on ME from the descriptor (-d) and relocates modules to free even more space(-r).  

Why was it chosen to not be applied?

**Comment by merge** [comment]
Thanks for your review! that's without a specific reason :) The thing is though, we won't ever create a larger image than our 4M, so saving space is not necessary here. Removing r/w permissions sounds reasonable though. I guess we should put up a PR to test that.
