### ISSUE TITLE
Boot is slower than expected

### ISSUE THREAD

**Issue by lukateras** [merge/skulls#78]
Thanks for the project! Happily running on several ThinkPad X230s :-)

That said, boot (both free and non-free VGA) seems to take around 2 seconds more than other Coreboot+SeaBIOS derivatives I have access to (APU2, Librem 13, also Coreboot+Tianocore Toshiba `swanky` Chromebook). What could be the reason behind that?

Judging by https://www.seabios.org/Runtime_config and https://github.com/coreboot/seabios/blob/14221cd86eadba82255fdc55ed174d401c7a0a04/src/boot.c#L466, there is an option `boot-menu-wait` that is set to 2.5 seconds by default. Since it is always possible to hold down Esc prior to boot, maybe that delay could be set to 0?

**Comment by merge** [comment]
I'm not sure. I think we really should leave users time to "press ESC". But there might still be ways to speed up things before that. Anyways, I'd be happy for hints or a patch :)

**Comment by pgera** [comment]
On my t530, I see a difference in warm reboot (fast) v/s cold reboot(slow). I'm talking about the delay before the splash, not the "press Esc" delay. This may be due to waiting for keyboard init.
