### ISSUE TITLE
tx and rx pins

### ISSUE THREAD

**Issue by Weythran** [merge/skulls#91]
What does one connect to the tx and rx pins on the raspberri board?

**Comment by merge** [comment]
Nothing if you use a keyboard and monitor. Otherwise, this is the serial console to use from your workstation.

How could we improve the documentation? thanks.

**Comment by Weythran** [comment]
I'll have a better idea how to improve documentation once i'm through the process. Currently I'm getting the error
"No EEPROM/flash device found.
Note: flashrom can never write if the flash chip isn't found automatically."

**Comment by merge** [comment]
That's unrelated to a serial connection to a RPi. That error suggests that you haven't wired up the SPI flash clip correctly.

**Comment by Weythran** [comment]
The pins look like they're connected properly to me. 
I'll try flashing using the second hardware method. What do we connect the GND wire on the Pomona clip to?

**Comment by merge** [comment]
to GND of the spi flasher.
