### ISSUE TITLE
Consider signing releases

### ISSUE THREAD

**Issue by asvc** [merge/skulls#92]
![2019-06-07_20-40](https://user-images.githubusercontent.com/300146/59100332-3e0f0100-8915-11e9-916a-da5e6515f57f.png)

Perhaps consider:
```gitconfig
[tag]
	gpgsign = true
```

**Comment by merge** [comment]
Look at release.sh. Don't I sign already? I might have used a new key though that github hasn't fetched yet...


Am 7. Juni 2019 13:13:31 MESZ schrieb Andrew Savchenko <notifications@github.com>:
>![2019-06-07_20-40](https://user-images.githubusercontent.com/300146/59100332-3e0f0100-8915-11e9-916a-da5e6515f57f.png)
>
>Perhaps consider:
>```gitconfig
>[tag]
>	gpgsign = true
>```

-- 
Martin Kepplinger
http://martinkepplinger.com
sent from mobile

**Comment by merge** [comment]
I've updated my key on github...
